[main]
shell = "bash"

font = RecMonoLinearNerdFontMono:size=12
font-bold = RecMonoLinearNerdFontMono:size=12:weight=bold
font-italic = RecMonoLinearNerdFontMono:size=12:slant=italic
font-bold-italic = RecMonoLinearNerdFontMono:size=12:weight=bold:slant=italic

font-size-adjustment = 1

line-height = 16
# letter-spacing
# horizontal/vertical-letter-offset
# underline-offset
# underline-thickness

box-drawings-uses-font-glyphs = yes

pad = 12x12
title = foot

[mouse]
hide-when-typing = yes

[colors]
alpha = 0.9

foreground = b0bec5
background = 1a1a1a

regular0 = 000000
regular1 = dc6068
regular2 = abcf76
regular3 = e6b455
regular4 = 6e98eb
regular5 = b480d6
regular6 = 71c6e7
regular7 = b0bec5

dim0 = 000000
dim1 = dc6068
dim2 = abcf76
dim3 = e6b455
dim4 = 6e98eb
dim5 = b480d6
dim6 = 71c6e7
dim7 = b0bec5

bright0 = 000000
bright1 = f07178
bright2 = c3e88d
bright3 = ffcb6b
bright4 = 82aaff
bright5 = c792ea
bright6 = 89ddff
bright7 = eeffff

selection-foreground = b0bec5
selection-background = 404040

[tweak]
font-monospace-warn = no
